### ISSUE TITLE
Clasificación de Mantenimiento

### ISSUE THREAD

**Issue by MarcoGonzalezE** [MarcoGonzalezE/Mantenimiento-Ticket#5]
- **PREVENTIVO**

- **CORRECTIVO**

**Comment by MarcoGonzalezE** [comment]
### Asunto del problema
Campo Categoría no toma valores de la lista ya definida (mantenimiento.categoria.xml)

### Tu ambiente
* ODOO 10.0
* Python 2.7
* Chrome

### Pasos para reproducir
Al ingresar a las Solicitudes de Mantenimiento y crear una nueva, en el campo Categoría al desplegar la lista de opciones deben aparecer los que ya están definidos.

### Comportamiento esperado
Al desplegar la lista que aparezcan las opciones

### Comportamiento actual
Solo te da la opción de crear una nueva categoría.

**Comment by makeplerc** [comment]
@MarcoGonzalezE Faltaba definir el xml en el manifest del modulo
