### ISSUE TITLE
Jefe de Granja

### ISSUE THREAD

**Issue by MarcoGonzalezE** [MarcoGonzalezE/Mantenimiento-Ticket#7]
### Asunto del problema
Auto-llenar el campo de Jefe de Granja con la relación que se tiene con la Granja. En la lista de Supervisores de Granja.

### Tu ambiente
* ODOO 10.0
* Python 2.7
* Chrome

### Pasos para reproducir
En la creación de nuevas solicitudes al llenar el campo Granja

### Comportamiento esperado
Se complete el registro de Jefe de Granja con la lista definida por cada Granja

### Comportamiento actual
Se ingresa de manera manual de una lista desplegable de todos los usuarios.

**Comment by makeplerc** [comment]
@MarcoGonzalezE  se genero la funcion onchange esto soluciona el problema

@api.onchange('category')
    def _compute_partner(self):
        categories = self.env['website.support.ticket.categories'].search([('id','=',self.category.id)],limit=1)
        self.partner_id = self.env['res.partner'].search([('id','=',categories.cat_user_ids.partner_id.id)])
